// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NewJsonGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "7b188d37-2126-4143-b8b8-1d0c0170dfb5";
        public const string Name = "Json Generator";
        public const string Description = @"Generates a json schema based on an assembly";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Martijn Maddens";
        public const string Tags = "";
    }
}
